
languageCode = "en-in"
title = "brijeshkrishna"
theme = "LoveIt"
enableEmoji = true


[params]
  dateFormat = "02-01-2006"
  title = "brijesh krishna"
  description = "This is my cool site"

[params.header.title]
  logo = "/profile.png"
  pre=" Brijesh"
  name = "Krishna"

[params.footer]
  enable = false
  
[params.page]
  author ="brijesh"
  twemoji = true
  lightgallery = true
  fraction = true
  fontawesome = true

[params.home.profile]
  enable = true
  title = "Brijesh krishna"
  subtitle = "Welcome to my site"
  typeit = true
  social = true
  avatarURL = "/profile.png"


[params.social]
  GitHub = "brijeshkrishna"
  Linkedin = "brijesh-krishna-274530243"
  Telegram = "EnemyRed"
  Email = "briijeshkrishnaga@gmail.com"

[params.typeit]
  duration = 0
  
[params.page.share]
      enable = false

[markup.highlight]
  noClasses = false


[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 1
  title = "Posts"

[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 2
  title = "categories"


[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 3
  title="about me"
